# Generated by Django 3.1.10 on 2021-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название задачи')),
                ('content', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('created', models.DateField(default='2021-05-09', verbose_name='Дата создания задачи')),
            ],
        ),
    ]
